# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy to Fly
on:
  push:
    branches: [main]

jobs:
  deploy:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  notify_success:
    needs: [deploy]
    if: ${{ needs.deploy.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Success
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          content: '✅ **Deployment Successful!** A new version deployed to production'
          color: 0x00ee00
          title: '**Deployment Details**'
          description: |
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.actor }}

  notify_failure:
    needs: [deploy]
    if: ${{ always() && needs.deploy.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify failure
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          color: 0xee0000
          content: '❌ **Deployment failed!** The pipeline encountered an error'
          title: '**Failure Details**'
          description: |
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.actor }}
            **Workflow:** ${{ github.workflow }}
            **Job:** deploy

            [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}})

